Algoritmo "Função"

// Descrição   : Exercícios de função (randi)
// Autor(a)    : Daniele Costa
// Descrição   : Programa desenvolvido a partir dos exercícios do curso de Lógica de Programação do SENAI.
// (eadnacional.cetiqt.senai.br/)
// Data atual  : 7/15/2020



inicio

//utilizará a função nativa de sorteio.

//Sorteará números de 0 à 10

escreval( randi(11))

fimalgoritmo






